//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broadcast.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Broadcast.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tr&gt;&lt;td&gt;&lt;a href=\&quot;thread-14312286-1-1.html\&quot; target=\&quot;_blank\&quot;&gt;App人气tcp协yi&lt;/a&gt;&lt;/td&gt;&lt;td&gt;&lt;font color=#FF6600&gt;&lt;b&gt;￥20000&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;&lt;td&gt;不需要&lt;/td&gt;&lt;td&gt;&lt;span title=\&quot;2019-2-12 21:19\&quot;&gt;昨天&amp;nbsp;21:19&lt;/span&gt;&lt;/td&gt;&lt;td&gt;&lt;a href=\&quot;./home.php?mod=space&amp;amp;uid=542555\&quot; target=\&quot;_blank\&quot;&gt;xy1513007&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;a href=\&quot;thread-14312036-1-1.html\&quot; target=\&quot;_blank\&quot;&gt;收IOS真机插件。抖音&lt;span&gt;APP&lt;/span&gt;&lt;/a&gt;&lt;/td&gt;&lt;td&gt;&lt;font color=#FF6600&gt;&lt;b&gt;￥20000&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;&lt;td&gt;不需要&lt;/td&gt;&lt;td&gt;&lt;span title=\&quot;2019-2-12 13:49\&quot;&gt;昨天&amp;nbsp;13:49&lt;/spa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestHtml {
            get {
                return ResourceManager.GetString("TestHtml", resourceCulture);
            }
        }
    }
}
